### ISSUE TITLE
CLI output truncated to first KB

### ISSUE THREAD

**Issue by ryangreenberg** [hhvm/hh-clilib#23]
For this CLI class:

```php
<?hh // strict
use type Facebook\CLILib\CLIWithArguments;
use namespace Facebook\CLILib\CLIOptions;
final class TruncateOutputCLI extends CLIWithArguments {
	<<__Override>>
	public async function mainAsync(): Awaitable<int> {
		$kb = str_repeat(".", 1023) . "\n";
		$output = str_repeat($kb, 4);
		$bytes = strlen($output);
		$bytes_written = $this->getTerminal()->getStdout()->write($output);
		// Same issue occurs with
		// echo str_repeat($kb, 4);
		echo "\n";
		echo "Bytes: " . strlen($output) . "\n";
		echo "Written: " . $bytes_written . "\n";
		return $bytes === $bytes_written ? 0 : 1;
	}
	public function getSupportedOptions(): vec<CLIOptions\CLIOption> {
		return vec[];
	}
}
```

Only the first 1023 bytes are output. This issue occurs for me with hhvm 3.28 and the current nightly on OSX.

See https://github.com/ryangreenberg/hh-clilib-repro for code to reproduce. My initial guess is that this has something to do with mainAsync being an `Awaitable` but I don't understand why that would be the case. When I step through this code in the debugger it outputs all the content.

**Comment by fredemmott** [comment]
https://github.com/hhvm/hacktest/issues/45

Neat; for some reason when I tried reproing it in isolation it was fine; will take another look now that there's an  isolated repro  - thanks :)

**Comment by fredemmott** [comment]
Though, this is both expected (it's why it returns bytes written), and bad API design (i.e. saying it's expected is not good :p ). Probably going to end up splitting the InputInterface/OutputInterface to separate low-level and high-level - low-level keeping this behavior, high-level providing user-friendly handling on top of this.

**Comment by ryangreenberg** [comment]
Makes sense, and this has a simple enough workaround for now.

The thing I didn't really understand is why both `fwrite` and `echo` showed the same behavior inside the CLI `mainAsync` method but seemed fine outside it (e.g. in the bin script).

**Comment by fredemmott** [comment]
The streams are set to non-blocking for the asynchronous stuff to work correctly; I should double check that’s actually needed, rather than a red herring caused by the now-resolved issues with HHVM+libevent2
